"""Initial migration

Revision ID: 3e916e573889
Revises: 
Create Date: 2025-01-02 13:08:35.936494

"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Table, UniqueConstraint
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = '3e916e573889'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Создание таблицы users
    op.create_table(
        'users',
        Column('id', Integer, primary_key=True, index=True),
        Column('uid', String, unique=True, nullable=False, default=str(uuid.uuid4())),
        Column('username', String, index=True, nullable=False),
    )

    # Создание таблицы private_chats
    op.create_table(
        'private_chats',
        Column('id', Integer, primary_key=True, index=True),
        Column('user_one_id', Integer, ForeignKey('users.id'), nullable=False),
        Column('user_two_id', Integer, ForeignKey('users.id'), nullable=False),
        UniqueConstraint('user_one_id', 'user_two_id', name='uix_user_chat'),
    )

    # Создание таблицы messages
    op.create_table(
        'messages',
        Column('id', Integer, primary_key=True, index=True),
        Column('chat_id', Integer, ForeignKey('private_chats.id'), nullable=False),
        Column('user_id', Integer, ForeignKey('users.id'), nullable=False),
        Column('text', String, nullable=False),
        Column('created_at', DateTime, default=datetime.now()),
        Column('updated_at', DateTime, default=datetime.now(), onupdate=datetime.now()),
        Column('emotion', String, nullable=True),
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
